#!/bin/sh

DIR="$(cd "$(dirname "$0")" && pwd)"
ANSIBLE_IMAGE=williamyeh/ansible
ANSIBLE_IMAGE_TAG=debian8
ANSIBLE_ENV="GOOGLE_APPLICATION_CREDENTIALS=./creds/serviceaccount.json"
ANSIBLE="docker run -e ${ANSIBLE_ENV} -v ${DIR}:/v -w /v  ${ANSIBLE_IMAGE}:${ANSIBLE_IMAGE_TAG} ansible-playbook"

eval ${ANSIBLE} $@